apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: api-conversao
        image: carloshsrosa/api-conversao:latest
        ports: 
        - containerPort: 8080   
---
apiVersion: v1
kind: Service
metadata: 
  name: api-conversao
spec: 
  selector:
    app: web
  ports: 
    - port: 8080
      protocol: TCP
      nodePort: 30000
  type: NodePort     